workflows:
  android-workflow:
    name: Android Workflow
    # ....
    environment:
      android_signing:
        - HD
    triggering:
      branch_patterns:
        - pattern: "master"
        - include: true
          source: true # pr merged
      cancel_previous_builds: true
    scripts:
    - name: Set up local.properties
      script: | 
        echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
    - name: Get Flutter packages
      script: | 
        flutter upgrade
        flutter packages pub get
    - name: Build AAB with Flutter
      script: | 
        flutter build appbundle --release
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log